---
kind: pipeline
name: default

steps:
- name: build Rust version
  image: rust:latest
  commands:
  - cargo build --release

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github-token
    files:
      - target/release/lagerist
    checksum:
      - sha256
  when:
    event: tag

- name: build python version
  image: plugins/docker
  settings:
    repo: docker.funzt-halt.net/lagerist
    tags: python
    dockerfile: Dockerfile.python
    cache_from: docker.funzt-halt.net/lagerist:python
  when:
    event:
      exclude:
      - pull_request

- name: build Rust docker image
  image: plugins/docker
  settings:
    repo: docker.funzt-halt.net/lagerist
    tags: rust
    dockerfile: Dockerfile.rust
  when:
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: b38ee3b2a89226532543c8c16fd4db9750dc68bef3589c36a87a63f58e559c86

...
