---
kind: pipeline
name: default

steps:
- name: build Rust version
  image: rust:latest
  commands:
  - cargo build --release

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github-token
    files:
      - target/release/lagerist
    checksum:
      - sha256
  when:
    event: tag

- name: build python version
  image: plugins/docker
  settings:
    repo: docker.funzt-halt.net/lagerist
    tags: python
    dockerfile: Dockerfile.python
    cache_from: docker.funzt-halt.net/lagerist:python
  when:
    event:
      exclude:
      - pull_request

- name: build Rust docker image
  image: plugins/docker
  settings:
    repo: docker.funzt-halt.net/lagerist
    tags: rust
    dockerfile: Dockerfile.rust
  when:
    event:
      exclude:
      - pull_request

- name: build public docker image
  image: plugins/docker
  settings:
    repo: svedrin/lagerist
    tags: latest
    username: svedrin
    dockerfile: Dockerfile.rust
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/lagerist:latest"
  when:
    branch: master
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: ae685fe6714f17d7ea381a09054184f82baf2f1720b96bf2bcda5a8a5fbe0157

...
