---
kind: pipeline
name: default

steps:
- name: build Rust version
  image: rust:alpine
  commands:
  - apk add --no-cache musl-dev
  - cargo build --release

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github-token
    files:
      - target/release/lagerist
    checksum:
      - sha256
  when:
    event: tag

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/lagerist
    tags: latest
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/lagerist:latest"
  when:
    branch: master
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: d2c20b5584302404bca3562ba77583c3eff65467a6042bd21a055ccafdfa362d

...
