---
kind: pipeline
name: default

steps:
- name: build Rust version
  image: rust:latest
  commands:
  - cargo build --release

- name: build python version
  image: plugins/docker
  settings:
    repo: docker.funzt-halt.net/lagerist
    tags: python
    dockerfile: Dockerfile.python
    cache_from: docker.funzt-halt.net/lagerist:python
  when:
    branch: master
    event:
      exclude:
      - pull_request

- name: build Rust docker image
  image: plugins/docker
  settings:
    repo: docker.funzt-halt.net/lagerist
    tags: rust
    dockerfile: Dockerfile.rust
  when:
    branch: master
    event:
      exclude:
      - pull_request

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github-token
    files:
      - target/release/lagerist
    checksum:
      - sha256
  when:
    #event: tag
    branch: master
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: f393115a1c98dafdb909b64753cabee0d674595a55c5fce58f9b7f3d7ad0707c

...
