[package]
name = "lagerist"
version = "0.1.0"
authors = ["Michael Ziegler <michael.ziegler@proemion.com>"]
edition = "2018"

[dependencies]
"clap" = "2.33"
"error-chain" = "*"
"prometheus" = "0.7"
"libc" = "0.2.62"
