[package]
name = "lagerist"
version = "0.1.1"
authors = ["Michael Ziegler <michael.ziegler@proemion.com>"]
edition = "2018"

[dependencies]
"clap" = "2.33"
"ctrlc" = "3.1.3"
"error-chain" = "*"
"libc" = "0.2.62"
"prometheus" = "0.7"
