[package]
name = "lagerist"
version = "0.1.2"
authors = ["Michael Ziegler <michael.ziegler@proemion.com>"]
edition = "2018"

[dependencies]
"clap" = "2.33"
"ctrlc" = { version="3.1.3", features=["termination"] }
"error-chain" = "*"
"libc" = "0.2.62"
"prometheus" = "0.7"
