FROM debian:buster-slim
RUN apt-get update && apt-get -y install dumb-init

COPY target/release/lagerist  /app/
WORKDIR /app

VOLUME ["/proc", "/sys", "/dev"]
EXPOSE 9165
ENTRYPOINT ["dumb-init", "--"]
CMD [ "/app/lagerist" ]

# run using: docker run --rm -it -v /proc:/proc:ro /dev:/dev:ro /sys:/sys lagerist
